##################################################################################################
# asn1scc
##################################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: asn1scc
  labels:
    app: asn1scc
spec:
  selector:
    matchLabels:
      app: asn1scc
  replicas: 1
  template:
    metadata:
      labels:
        app: asn1scc
    spec:
      #nodeName: master
      containers:
        - name: asn1scc
          image: lucasor99/asn1scc:latest
          securityContext:
            runAsUser: 0
          env:
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: CASSANDRA_PASSWORD
          ports:
            - containerPort: 5000  
---
apiVersion: v1
kind: Service
metadata:
  name: asn1scc
spec:
  selector:
    app: asn1scc
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


