apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=  # "admin" codificado en base64 (echo -n 'admin' | base64)
  CASSANDRA_PASSWORD: YWRtaW4=  # "admin" codificado en base64
  DJANGO_SECRET_KEY: YWRtaW4=  # "admin" codificado en base64
