##################################################################################################
# Auto Ground Station
##################################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: lucasor99/auto-gs-web:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
          command: ["/bin/sh", "-c", "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          securityContext:
            runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    service: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 8000
      name: http
      targetPort: 8000
      nodePort: 30000
